spring:
  thymeleaf:
    cache: false
    excluded-view-names: db  # 排除 h2-console 页面
#    enabled: false

  datasource:
    url: jdbc:sqlite::resource:db/blog.sqlite
    driver-class-name: org.sqlite.JDBC
    #建表语句
    schema: classpath:db/schema.sql
    #dml添加数据

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  profiles:
    active: pro

  mail:
    host: smtp.qq.com
    port: 465
    username: 212842183@qq.com
    password: cwdonrpkfvavcbci
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

mybatis:
  type-aliases-package: com.yikolemon.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagesize: 8
msgsize: 6

qiniu:
  access_key: XKB8qnTudEjAUUAHk01-p44QV5mGc6b2VsxrKL2o
  secret_key: Or1Gkzxgi0jq-ZnjA2T3NKtOmYTtIZ9SIaZwaL00
  bucketname: yikolemon-blog
  domain: cdn.yikolemon.cn/





