spring:
  mail:
    host: smtp.qq.com
    port: 465
    password: dackruorwsfxbieb
    username: 212842183@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  rabbitmq:
    addresses: 192.168.56.10
    username: guest
    password: 123456
    port: 5672

logging:
  level:
    root: info
    com.yikolemon: debug
  file:
    name: mail-log/blog-dev.log
  config: classpath:logback-spring.xml


