spring:
  mail:
    host: smtp.qq.com
    port: 465
    password: dackruorwsfxbieb
    username: 212842183@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    port: 6666
    host: 127.0.0.1
    database: 0
    jedis:
      pool:
        min-idle:   0
        max-active: 8
        max-wait: -1ms
        max-idle:   8

  rabbitmq:
    addresses: 192.168.56.10
    username: guest
    password: 123456
    port: 5672

logging:
  level:
    root: info
    com.yikolemon: debug
  file:
    name: mail-log/blog-dev.log
  config: classpath:logback-spring.xml


elasticsearch:
  host: 101.43.244.40
  port: 9200


