spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  profiles:
    active: dev
  redis:
    port: 6666
    host: 127.0.0.1
    database: 0
    jedis:
      pool:
        min-idle:   0
        max-active: 8
        max-wait: -1ms
        max-idle:   8
  mail:
    host: smtp.qq.com
    port: 465
    username: 212842183@qq.com
    password: iirzafmmltvsbhfh
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    addresses: 192.168.56.10
    username: guest
    password: 123456
    port: 5672

mybatis:
  type-aliases-package: com.yikolemon.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagesize: 8
msgsize: 6

elasticsearch:
  host: 101.43.244.40
  port: 9200

custom-manager:
  isOpen-custom-cache: true
  cache-type: caffeine-redis



